<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-CHVHII7" failures="4" tests="40" name="primes.PrimesTests" time="18.308" errors="0" timestamp="2021-02-17T21:41:30 GMT" skipped="0">
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.440"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.376"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.299"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.304"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.352"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.376"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.416"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.312">
    <failure message="Testcase 18 has incorrect Status Code: expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase 18 has incorrect Status Code: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at primes.PrimesTests.testStatusCodeEquals400(PrimesTests.java:43)
at jdk.internal.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- testStatusCodeEquals400 -->
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.467"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.304"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.304"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.403"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.304"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.296"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.310">
    <failure message="Testcase 3 has incorrect Status Code: expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase 3 has incorrect Status Code: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at primes.PrimesTests.testStatusCodeEquals400(PrimesTests.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- testStatusCodeEquals400 -->
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.406"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.552"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.408"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.554"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.984"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.328"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.264"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.480"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.312"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.352"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.312"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.304"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.304"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.264"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.400"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.843"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.312"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.632"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.393">
    <failure message="Testcase 11 has incorrect Status Code: expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase 11 has incorrect Status Code: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at primes.PrimesTests.testStatusCodeEquals400(PrimesTests.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- testStatusCodeEquals400 -->
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="2.721"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.296"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.520"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals400" time="0.328">
    <failure message="Testcase 10 has incorrect Status Code: expected [400] but found [200]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Testcase 10 has incorrect Status Code: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at primes.PrimesTests.testStatusCodeEquals400(PrimesTests.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- testStatusCodeEquals400 -->
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.336"/>
  <system-out/>
  <testcase classname="primes.PrimesTests" name="testStatusCodeEquals200" time="0.440"/>
  <system-out/>
</testsuite> <!-- primes.PrimesTests -->
